package com.talhanation.bannermod.network.catalog;

import com.talhanation.bannermod.network.messages.military.*;

/**
 * Military packet catalog, registered first on the shared BannerMod channel.
 * Order is the legacy recruits.Main setup order and must remain stable.
 */
public final class MilitaryPacketCatalog {
    public static final Class<?>[] MESSAGES = {
        MessageMovement.class,
        MessageCommandScreen.class,
        MessageRecruitGui.class,
        MessageHire.class,
        MessageHireGui.class,
        MessageDisband.class,
        MessageRest.class,
        MessageAttack.class,
        MessageAggro.class,
        MessageAggroGui.class,
        MessageListen.class,
        MessageProtectEntity.class,
        MessageMountEntity.class,
        MessageMountEntityGui.class,
        MessageDismount.class,
        MessageDismountGui.class,
        MessageBackToMountEntity.class,
        MessageRangedFire.class,
        MessageStrategicFire.class,
        MessageShields.class,
        MessageGroup.class,
        MessageSplitGroup.class,
        MessageMergeGroup.class,
        MessageDisbandGroup.class,
        MessageSetLeaderGroup.class,
        MessageRecruitCount.class,
        MessageAssassinCount.class,
        MessageAssassinGui.class,
        MessageAssassinate.class,
        MessageFaceCommand.class,
        MessageTeleportPlayer.class,
        MessageScoutTask.class,
        MessageFollowGui.class,
        MessageClearTarget.class,
        MessageClearTargetGui.class,
        MessageOpenSpecialScreen.class,
        MessageOpenPromoteScreen.class,
        MessageOpenDisbandScreen.class,
        MessageToClientOpenNobleTradeScreen.class,
        MessageHireFromNobleVillager.class,
        MessageWriteSpawnEgg.class,
        MessageDoPayment.class,
        MessageUpkeepEntity.class,
        MessageUpkeepPos.class,
        MessageClearUpkeep.class,
        MessageClearUpkeepGui.class,
        MessageToClientUpdateOnlinePlayers.class,
        MessageSendMessenger.class,
        MessageAnswerMessenger.class,
        MessageToClientOpenMessengerAnswerScreen.class,
        MessageToClientUpdateMessengerScreen.class,
        MessageToClientUpdateHireState.class,
        MessageToClientUpdateClaim.class,
        MessageToClientUpdateClaims.class,
        MessageUpdateClaim.class,
        MessageReassignClaimPoliticalEntity.class,
        MessageDeleteClaim.class,
        MessageClaimIntent.class,
        MessageToClientReceiveRoute.class,
        MessageTransferRoute.class,
        MessageToClientUpdateGroups.class,
        MessageUpdateGroup.class,
        MessageAssignGroupToPlayer.class,
        MessageAssignGroupToCompanion.class,
        MessageRemoveAssignedGroupFromCompanion.class,
        MessageAssignNearbyRecruitsInGroup.class,
        MessageApplyNoGroup.class,
        MessageToClientUpdateUnitInfo.class,
        MessageToClientUpdateLeaderScreen.class,
        MessageSaveFormationFollowMovement.class,
        MessageFormationFollowMovement.class,
        MessagePatrolLeaderSetRoute.class,
        MessagePatrolLeaderAddWayPoint.class,
        MessagePatrolLeaderRemoveWayPoint.class,
        MessagePatrolLeaderSetCycle.class,
        MessagePatrolLeaderSetPatrolState.class,
        MessagePatrolLeaderSetPatrollingSpeed.class,
        MessagePatrolLeaderSetWaitTime.class,
        MessagePatrolLeaderSetEnemyAction.class,
        MessagePatrolLeaderSetInfoMode.class,
        MessageToClientSetToast.class,
        MessagePromoteRecruit.class,
        MessageOpenGovernorScreen.class,
        MessageToClientUpdateGovernorScreen.class,
        MessageUpdateGovernorPolicy.class,
        MessageDebugGui.class,
        MessageDebugScreen.class,
        MessageAdminRecruitSpawn.class,
        MessageSelectRecruits.class,
        MessageCombatStance.class,
        MessageCombatStanceGui.class,
        MessageAssignRecruitToPlayer.class,
        MessageRequestFormationMapSnapshot.class,
        MessageToClientUpdateFormationMapSnapshot.class,
        MessageFormationMapMoveOrder.class,
        MessageFormationMapEngage.class,
        MessageConvertRecruitType.class,
        MessageRequestPerkTreeSnapshot.class,
        MessageUpdatePerkTree.class,
        MessageToClientUpdatePerkTreeSnapshot.class,
    };

    public static final PacketCatalog CATALOG = new PacketCatalog(MESSAGES);

    private MilitaryPacketCatalog() {
    }
}
